Django_Level_Four/templatesproj/templatesapp/urls.py
from django.conf.urls import url;
from templatesapp import views;

#Template Tagging for relative url template usage ...
app_name = 'templatesapp';

urlpatterns = [
    # for relative templete tagging usage ...
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
];

Django_Level_Four/templatesproj/templatesproj/urls.py
from django.conf.urls import url, include;
from django.contrib import admin;
from templatesapp import views;

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^templatesapp/', include('templatesapp.urls')),
]

Django_Level_Four/templatesproj/templatesapp/models.py
from django.db import models

# Create your models here.

Django_Level_Four/templatesproj/templatesapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': 'Hello, World!', 'number': 2122}
    return render(request, 'templatesapp/index.html', context_dict);

def other(request):
    return render(request, 'templatesapp/other.html');

def relative(request):
    return render(request, 'templatesapp/rel_url_templates.html');

Django_Level_Four/templatesproj/templates/templatesapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- My CSS style sheet -->
    <link rel="stylesheet" href='{% static "css/my_style.css" %}'>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class = "navbar navbar-default navbar-static-top">
      <div class = "container">
        <ul class = "nav navbar-nav">
          <li><a class = "navbar-brand" href = "{% url 'index' %}">Brand</a></li>
          <li><a class = "navbar-link" href = "{% url 'templatesapp:other' %}">Other</a></li>
          <li><a class = "navbar-link" href = "{% url 'admin:index' %}">Admin</a></li>
        </ul>
      </div>
    </nav>
    <div class = "container">
      {% block body_block %}
      <!-- Anything outdide of this block will be inherited if you extend!  -->
      {% endblock %}
    </div>
  </body>
</html>

Django_Level_Four/templatesproj/templates/templatesapp/index.html
{% extends "templatesapp/base.html" %}
  {% load myextras %}
  {% block body_block %}
    <ul class = "nodots">
      <li><h1>Welcome to the Index Page!</h1></li>
      <li><h2>This is the index.html page showing.</h2></li>
      <li><h4>{{ text|cut:", World" }} {{ number|add:"22" }}</h4></li>
    </ul>
  {% endblock %}

Django_Level_Four/templatesproj/templates/templatesapp/other.html
{% extends "templatesapp/base.html" %}
  {% block body_block %}
    <ul class = "nodots">
      <li><h1>Welcome to the Other page!</h1></li>
      <li><h2>This is an example of template inheritance!</h2></li>
    </ul>
  {% endblock %}

Django_Level_Four/templatesproj/templates/templatesapp/rel_url_templates.html
{% extends "templatesapp/base.html" %}
  {% block body_block %}
    <ul class = "nodots">
      <li><h1>Welcome to Relative URL Template Page!</h1></li>
      <li><h2><a href = "{% url 'index' %}">Link to the Index page ...</a></h2></li>
      <li><h2><a href = "{% url 'templatesapp/other' %}">Link to the Other page ...</a></h2></li>
      <li><h2><a href = "{% url 'admin:index' %}">Link to the Admin panel ...</a></h2></li>
    </ul>
    {% endblock %}